### ISSUE TITLE
[Bug] JavaCC throws an Error [sf#65]

### ISSUE THREAD

**Issue by patrickwestphal** [AKSW/DL-Learner#10]
**Reported by kurzum on 2010-08-19 13:17 UTC**
in:
public class TokenMgrError extends Error
This eror is sometimes not caught and transformed to the checked Exception.
So effectively, if an Application uses 
try\{\} catch \(ParseException e\) \{\} 
the error can still run through and wreck the application

\[ERROR\] org.dllearner.parser.TokenMgrError: Lexical error at line 1, column 8.  Encountered: "a" \(97\), after : "F"
\[ERROR\] 	at org.dllearner.parser.KBParserTokenManager.getNextToken\(parser:KBParserTokenManager.java\):1309\)
\[ERROR\] 	at org.dllearner.parser.KBParser.jj\_ntk\(parser:KBParser.java\):1219\)
\[ERROR\] 	at org.dllearner.parser.KBParser.Concept\(parser:KBParser.java\):425\)
\[ERROR\] 	at org.dllearner.parser.KBParser.TBoxEquiv\(parser:KBParser.java\):267\)
\[ERROR\] 	at org.dllearner.parser.KBParser.parseConcept\(parser:KBParser.java\):30\)
\[ERROR\] 	at org.nlp2rdf.navigator.server.store.LogicalRelationStrategy.add\(LogicalRelationStrategy.java:132\)
\[ERROR\] 	at org.nlp2rdf.navigator.server.store.LogicalRelationStrategy.update\(LogicalRelationStrategy.java:154\)
\[ERROR\] 	at org.nlp2rdf.navigator.server.store.Store.saveConcept\(Store.java:39\)

**Comment by LorenzBuehmann** [comment]
The problem description is not clear. A ParseException is thrown if something wasn't correct and the parser was created by JavaCC. If an application catches the exception and ignores it, it is its own fault.

I'll close this issue because I don't see any choice to solve it in the DL-Learner framework.
