### ISSUE TITLE
[Bug] Missing warning for positives that are negatives [sf#66]

### ISSUE THREAD

**Issue by patrickwestphal** [AKSW/DL-Learner#11]
**Reported by kurzum on 2010-08-25 13:47 UTC**
In general, if you assign the same instance as positive and negative example \(e.g. by mistake\)
there is no warning or error message, which is direly needed. 
It is quite a common copy and paste mistake and takes forever, if there is no warning.

**Comment by patrickwestphal** [comment]
**Updated by kurzum on 2010-08-25 13:48 UTC**
- **assigned_to**: nobody --> jenslehmann

**Comment by LorenzBuehmann** [comment]
Fixed. A warning is returned if an individual is declared as both, positive and negative example.
