### ISSUE TITLE
Ignored concepts/properties not taken into account by refinement operator

### ISSUE THREAD

**Issue by LorenzBuehmann** [AKSW/DL-Learner#43]
## Problem:
Class expression learning algorithms derived from `AbstractCELA` allow to set classes and object/data properties that should be ignored during learning. Those ignored entities are only considered during the initialization of the hierarchies in
`initClassHierarchy()`
`initObjectPropertyHierarchy()`
`initDataPropertyHierarchy()`

Those hierarchy objects are put into the refinement operator. The problem is that for some tasks only the underlying reasoner is used:

```Java
if(useNumericDatatypes) {
			Set<OWLDataProperty> numericDPs = reasoner.getNumericDataProperties();
```

or

```Java
if(useDataHasValueConstructor) {
			Set<OWLDataProperty> stringDPs = reasoner.getStringDatatypeProperties();
```

and even in the `init()` method.

This can lead to solutions that can contain ignored entities, thus, should not be returned and also cause a larger search space than necessary.

**Comment by SimonBin** [comment]
hopefully fixed by #48
