### ISSUE TITLE
[Feature] AutoSPARQL: no repetition of query trees [sf#43]

### ISSUE THREAD

**Issue by patrickwestphal** [AKSW/DL-Learner#5]
**Reported by jenslehmann on 2010-12-13 10:50 UTC**
When a user is asked as question about whether a resource r is in the result set, then the query tree corresponding to r should not be the same as some query tree corresponding to a resource r' for which a question has been asked previously.

**Comment by LorenzBuehmann** [comment]
This interactive behaviour is not part of the DL-Learner, but the AutoSPARQL project.
