### ISSUE TITLE
[Bug] error in Description object [sf#51]

### ISSUE THREAD

**Issue by patrickwestphal** [AKSW/DL-Learner#7]
**Reported by kurzum on 2010-02-16 21:53 UTC**
run 
examples/testCaseSPARQLDescription
add in ROLlearner2
SparqlQueryDescriptionConvertVisitor visit = new SparqlQueryDescriptionConvertVisitor\(\);
String sparqlQuery = visit.getSparqlQuery\(ed.getDescription\(\).toKBSyntaxString\(\)\);
and 
String sparqlQuery = visit.getSparqlQuery\(ed.getDescription\(\)\);

**Comment by patrickwestphal** [comment]
**Commented by jenslehmann on 2010-03-05 09:34 UTC**
Where should I add this piece of code \(in particular, "ed" is not defined\) and which of the conf files should be used?

**Comment by patrickwestphal** [comment]
**Commented by jenslehmann on 2010-08-06 12:53 UTC**
Test files have been moved from /examples/testCaseSPARQLDescription to /test/testCaseSPARQLDescription. Please refine the bug description.

**Comment by LorenzBuehmann** [comment]
This bug report is outdated and the conversion of class expressions was superceded by another implementation.
