### ISSUE TITLE
[Bug] Long time while switching panels [sf#53]

### ISSUE THREAD

**Issue by patrickwestphal** [AKSW/DL-Learner#8]
**Reported by lorenz_b on 2010-02-21 22:30 UTC**
When loading this ontology, and repairing the inconsistency the programm needs long time and goes to the unsatisfiable panel, although there is no need to do so.

http://owl.cs.manchester.ac.uk/repository/download?ontology=http://lsdis.cs.uga.edu/projects/glycomics/propreo&format=RDF/XML

**Comment by LorenzBuehmann** [comment]
You are loading it with which tool? Are you really talking about the DL-Learner?

**Comment by LorenzBuehmann** [comment]
Unrelated
